AllCops:
  NewCops: enable
  TargetRubyVersion: 3
  TargetChefVersion: 17
  DefaultFormatter: progress
  DisplayCopNames: true
  DisplayStyleGuide: true
  StyleGuideBaseURL: https://rubystyle.guide
  ExtraDetails: true

Layout/LineLength:
  Max: 160

Metrics/ModuleLength:
  Max: 300

Metrics/MethodLength:
  Max: 100

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
